### ISSUE TITLE
網站能不能默認一個國家例如美國香港

### ISSUE THREAD

**Issue by killsting** [coder-ysj/jayyan.net-itunes#1]
因為現在每次打開都要選擇一個美國比較麻煩，或者記住上次選擇的選項也不錯。

**Comment by killsting** [comment]
還有可以不可以默認高清是 1400 X 1400，因為現在 iTunes 買的數字專輯內嵌就已經是這麽大了。

**Comment by coder-ysj** [comment]
1. 记住选项会加上。
2. 默认分辨率暂时不会改，因为还得考虑到其他人的其它用途。不过以后可能会加上自定义分辨率选项，方便自制。
